user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

produit_categorie.produit:
    resource: "@ProduitBundle/Controller/Categorie_ProduitController.php"
    type:     annotation

produit_sous.categorie:
    resource: "@ProduitBundle/Controller/Sous_categorieController.php"
    type:     annotation

produit_produit:
    resource: "@ProduitBundle/Controller/ProduitController.php"
    type:     annotation

produit:
    resource: "@ProduitBundle/Resources/config/routing.yml"
    prefix:   /

template:
    resource: "@TemplateBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
