<?php

namespace ProduitBundle\Repository;

/**
 * Categorie_ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Categorie_ProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
