<?php

namespace ProduitBundle\Repository;

/**
 * Sous_categorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Sous_categorieRepository extends \Doctrine\ORM\EntityRepository
{
}
