template_homepage:
    path:     /
    defaults: { _controller: TemplateBundle:Template:index }
template:
    path : /ma_layout
    defaults: { _controller: TemplateBundle:Template:index }
template_back:
    path : /admin
    defaults: { _controller: TemplateBundle:Template:back }
