<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBr6u0ay\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBr6u0ay/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerBr6u0ay.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerBr6u0ay\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerBr6u0ay\appDevDebugProjectContainer([
    'container.build_hash' => 'Br6u0ay',
    'container.build_id' => 'ddd1197c',
    'container.build_time' => 1581153350,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBr6u0ay');
