<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3d3xj5n\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3d3xj5n/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container3d3xj5n.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container3d3xj5n\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container3d3xj5n\appDevDebugProjectContainer([
    'container.build_hash' => '3d3xj5n',
    'container.build_id' => '60c4f797',
    'container.build_time' => 1581240763,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3d3xj5n');
